spring.application.name=real-time-app
spring.datasource.url=jdbc:postgresql://localhost:5432/realtime
spring.datasource.username=postgres
spring.datasource.password=Askaruly17
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true